default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twist_dev
  username: postgres
  password: password1
  host: localhost

test:
  <<: *default
  database: twist_test
  username: postgres
  password: password1
  host: localhost

